
version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker login -u sesha10 -p Badminto0
            docker build -t sesha10/docker-react .
