version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: docker build -t sesha10/docker-react -f Dockerfile.dev .

      - run:
          name: Run Tests
          command: docker run sesha10/docker-react npm run test -- --coverage

  # deploy:
  #   docker:
  #     - image: circleci/python:3.7

  #   working_directory: ~/repo

  #   steps:
  #     - checkout

  #     - run:
  #         name: Deploy to Elastic Beanstalk
  #         command: |
  #           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  #           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  #           aws configure set region $AWS_REGION
  #           eb deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master

      # - deploy:
      #     filters:
      #       branches:
      #         only: master
